decisao.web/src/main/java/br/jus/stf/estf/decisao/pesquisa/domain/ComunicacaoDto.java
package br.jus.stf.estf.decisao.pesquisa.domain;

import java.util.Date;
import java.util.List;

import br.gov.stf.estf.documento.model.util.ComunicacaoDocumentoResult;
import br.gov.stf.estf.entidade.documento.Comunicacao;
import br.gov.stf.estf.entidade.documento.PecaProcessoEletronicoComunicacao;
import br.gov.stf.estf.entidade.processostf.Processo;
import br.gov.stf.estf.entidade.processostf.TipoMeioProcesso;
import br.jus.stf.estf.decisao.documento.support.Documento;
import br.jus.stf.estf.decisao.support.query.Dto;

public class ComunicacaoDto implements Dto, Documento {	
	
	private static final long serialVersionUID = -3188252336226511543L;
	
	private Long id;
	private Long idDocumentoComunicacao;
	private String dscNomeDocumento;
	private String processo;
	private String faseComunicacaoAtual;
	private String nomeMinistroRelator;
	private Long idSetorMinistro;
	private String ministro;
	private String nomeMinistro;	
	private Date dataCriacao;
	private Date dataDisponibilizacaoGabinete;
	private boolean selected;
	private Long idArquivoEletronico;
	private Long idObjetoIncidente;
	private String usuarioCriacao;
	private TipoMeioProcesso tipoMeioProcesso;
	private List<PecaProcessoEletronicoComunicacao> pecasProcessoEletronico;
	private String descricaoStatusDocumento;
	private Long idModeloComunicacao;

	/**
	 * Monta um Objeto ComunicacaoDto, por meio de um
	 * ComunicacaoDocumentoResult
	 * @param comunicacaoDocumentoResult
	 * @return
	 */
	public static ComunicacaoDto valueOf(ComunicacaoDocumentoResult comunicacaoDocumentoResult) {
		ComunicacaoDto dto = new ComunicacaoDto();
		dto.setId(comunicacaoDocumentoResult.getComunicacao().getId());
		dto.setIdDocumentoComunicacao(comunicacaoDocumentoResult.getDocumentoComunicacao().getId());
		dto.setProcesso(ObjetoIncidenteDto.valueOf(comunicacaoDocumentoResult.getComunicacao().getObjetoIncidenteUnico()).getIdentificacao());
		dto.setNomeMinistroRelator(comunicacaoDocumentoResult.getComunicacao().getNomeMinistroRelator());
		dto.setUsuarioCriacao(comunicacaoDocumentoResult.getComunicacao().getUsuarioCriacao());
		dto.setDscNomeDocumento(comunicacaoDocumentoResult.getComunicacao().getDscNomeDocumento());
		dto.setFaseComunicacaoAtual(comunicacaoDocumentoResult.getComunicacao().getFaseAtual());
		dto.setDataDisponibilizacaoGabinete(comunicacaoDocumentoResult.getComunicacao().getDeslocamentoAtual().getDataEntrada());
		dto.setPecasProcessoEletronico(comunicacaoDocumentoResult.getComunicacao().getPecasProcessoEletronico());		
		dto.setDescricaoStatusDocumento(comunicacaoDocumentoResult.getDocumentoComunicacao().getDocumentoEletronico().getDescricaoStatusDocumento());
		dto.setIdModeloComunicacao(comunicacaoDocumentoResult.getComunicacao().getModeloComunicacao().getId());
		return dto;
	}
	
	public static ComunicacaoDto valueOfForMobile(ComunicacaoDocumentoResult comunicacaoDocumentoResult) {
		ComunicacaoDto dto = new ComunicacaoDto();
		dto.setId(comunicacaoDocumentoResult.getComunicacao().getId());		
		dto.setProcesso(ObjetoIncidenteDto.valueOfForMobile(comunicacaoDocumentoResult.getComunicacao().getObjetoIncidenteUnico()).getIdentificacao());				
		dto.setDscNomeDocumento(comunicacaoDocumentoResult.getComunicacao().getDscNomeDocumento());		
		dto.setDataDisponibilizacaoGabinete(comunicacaoDocumentoResult.getComunicacao().getDeslocamentoAtual().getDataEntrada());		
		return dto;
	}
		
	
	/**
	 * @see br.jus.stf.estf.decisao.support.query.Dto#getId()
	 **/
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public Long getIdDocumentoComunicacao() {
		return idDocumentoComunicacao;
	}

	public void setIdDocumentoComunicacao(Long idDocumentoComunicacao) {
		this.idDocumentoComunicacao = idDocumentoComunicacao;
	}

	public String getDscNomeDocumento() {
		return dscNomeDocumento;
	}

	public void setDscNomeDocumento(String dscNomeDocumento) {
		this.dscNomeDocumento = dscNomeDocumento;
	}

	public String getNomeMinistroRelator() {
		return nomeMinistroRelator;
	}

	public void setNomeMinistroRelator(String nomeMinistroRelator) {
		this.nomeMinistroRelator = nomeMinistroRelator;
	}
	
	public Long getIdSetorMinistro() {
		return idSetorMinistro;
	}
	
	public void setIdSetorMinistro(Long idSetorMinistro) {
		this.idSetorMinistro = idSetorMinistro;
	}
	
	public Long getIdModeloComunicacao() {
		return idModeloComunicacao;
	}
	
	public void setIdModeloComunicacao(Long idModeloComunicacao) {
		this.idModeloComunicacao = idModeloComunicacao;
	}
	public String getNomeMinistro() {
		return nomeMinistro;
	}

	public void setNomeMinistro(String nomeMinistro) {
		this.nomeMinistro = nomeMinistro;
	}
	
	public String getMinistro() {
		return ministro;
	}

	public void setMinistro(String ministro) {
		this.ministro = ministro;
	}

	public String getFaseComunicacaoAtual() {
		return faseComunicacaoAtual;
	}

	public void setFaseComunicacaoAtual(String faseComunicacaoAtual) {
		this.faseComunicacaoAtual = faseComunicacaoAtual;
	}

	public Date getDataCriacao() {
		return dataCriacao;
	}

	public void setDataCriacao(Date dataCriacao) {
		this.dataCriacao = dataCriacao;
	}
	
	
	public Date getDataDisponibilizacaoGabinete() {
		return dataDisponibilizacaoGabinete;
	}

	public void setDataDisponibilizacaoGabinete(Date dataDisponibilizacaoGabinete) {
		this.dataDisponibilizacaoGabinete = dataDisponibilizacaoGabinete;
	}


	public void setIdArquivoEletronico(Long idArquivoEletronico) {
		this.idArquivoEletronico = idArquivoEletronico;
	}

	public Long getIdArquivoEletronico() {
		return idArquivoEletronico;
	}

	/**
	 * @see br.jus.stf.estf.decisao.support.query.Selectable#isSelected()
	 */
	public boolean isSelected() {
		return selected;
	}

	/**
	 * @see br.jus.stf.estf.decisao.support.query.Selectable#setSelected(boolean)
	 */
	public void setSelected(boolean selected) {
		this.selected = selected;
	}

	public String getProcesso() {
		return processo;
	}

	public void setProcesso(String objetoIncidente) {
		this.processo = objetoIncidente;
	}
	
	public Long getIdObjetoIncidente() {
		return idObjetoIncidente;
	}

	public void setIdObjetoIncidente(Long idObjetoIncidente) {
		this.idObjetoIncidente = idObjetoIncidente;
	}
	

	private static void adicionaTipoMeioProcesso(ComunicacaoDto dto, Comunicacao comunicacao) {
		Processo processo = (Processo) comunicacao.getObjetoIncidenteUnico().getPrincipal();
		if (processo != null){
			dto.setTipoMeioProcesso(processo.getTipoMeioProcesso());
		}
	}

	/**
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	public boolean equals(Object other) {
		if (!(other instanceof ComunicacaoDto)) {
			return false;
		}
		ComunicacaoDto castOther = (ComunicacaoDto) other;
		if (getId() != null && castOther.getId() != null) {
			return this.getId().equals(castOther.getId());
		}
		return false;
	}

	/**
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		return (getId() != null) ? getId().hashCode() : super.hashCode();
	}

	/**
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		String descricao = processo;
		if (getDscNomeDocumento() != null && !getDscNomeDocumento().equals("")) {
			descricao += " - " + getDscNomeDocumento();
		}
		
		if (descricao != null) {
			return descricao;
		} else {
			return getId().toString();
		}
	}

	public String getUsuarioCriacao() {
		return usuarioCriacao;
	}

	public void setUsuarioCriacao(String usuarioCriacao) {
		this.usuarioCriacao = usuarioCriacao;
	}
	
	public TipoMeioProcesso getTipoMeioProcesso() {
		return tipoMeioProcesso;
	}
	
	public void setTipoMeioProcesso(TipoMeioProcesso tipoMeioProcesso) {
		this.tipoMeioProcesso = tipoMeioProcesso;
	}
	
	public Boolean getEletronico(){
		return TipoMeioProcesso.ELETRONICO.equals(getTipoMeioProcesso());
	}
	
	
	public List<PecaProcessoEletronicoComunicacao> getPecasProcessoEletronico() {
		return pecasProcessoEletronico;
	}

	public void setPecasProcessoEletronico(
			List<PecaProcessoEletronicoComunicacao> pecasProcessoEletronico) {
		this.pecasProcessoEletronico = pecasProcessoEletronico;
	}

	@Override
	public boolean isFake() {
		return false;
	}

	public String getDescricaoStatusDocumento() {
		return descricaoStatusDocumento;
	}

	public void setDescricaoStatusDocumento(String descricaoStatusDocumento) {
		this.descricaoStatusDocumento = descricaoStatusDocumento;
	}
	
	
}

decisao.web/src/main/java/br/jus/stf/estf/decisao/objetoincidente/web/AbstractExportarProcessosActionFacesBean.java
package br.jus.stf.estf.decisao.objetoincidente.web;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;

import br.gov.stf.estf.entidade.processostf.ObjetoIncidente;
import br.gov.stf.estf.entidade.usuario.UsuarioIncidentePesquisa;
import br.gov.stf.estf.entidade.usuario.UsuarioIncidentePesquisa.UsuarioIncidentePesquisaId;
import br.gov.stf.estf.usuario.model.service.UsuarioIncidentePesquisaService;
import br.gov.stf.framework.model.service.ServiceException;
import br.jus.stf.estf.decisao.support.action.support.ActionSupport;

public abstract class AbstractExportarProcessosActionFacesBean<T> extends ActionSupport<T> {
		
	
	@Autowired
	private UsuarioIncidentePesquisaService usuarioIncidentePesquisaService;
	
private String message;
	
	
	public void load(){
		List<ObjetoIncidente<?>> objetosIncidentes = getListaObjetosIncidentes();
		if (objetosIncidentes != null && !objetosIncidentes.isEmpty()){
			List<UsuarioIncidentePesquisa> listaExportacao = new ArrayList<UsuarioIncidentePesquisa>();
			
			usuarioIncidentePesquisaService.apagarListaExportacao(getUsuario().getId().toUpperCase());
						
			for (ObjetoIncidente<?> objetoIncidente : objetosIncidentes){
				UsuarioIncidentePesquisaId uipId = new UsuarioIncidentePesquisaId();
				UsuarioIncidentePesquisa uip = new UsuarioIncidentePesquisa();
				
				uipId.setSeqObjetoIncidente(objetoIncidente.getId());
				uipId.setSigUsuario(getUsuario().getId().toUpperCase());				
				uip.setId(uipId);
				listaExportacao.add(uip);
			}
			if (!listaExportacao.isEmpty()){
				try {
					usuarioIncidentePesquisaService.incluirTodos(listaExportacao);
					sendToConfirmation();
				} catch (ServiceException e) {
					addError("Ocorreu um erro ao exportar a lista de processos: " + e.getMessage());
				}
			}	
		}
	}
		

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}
	
	protected abstract List<ObjetoIncidente<?>> getListaObjetosIncidentes();	


	public UsuarioIncidentePesquisaService getUsuarioIncidentePesquisaService() {
		return usuarioIncidentePesquisaService;
	}


	public void setUsuarioIncidentePesquisaService(
			UsuarioIncidentePesquisaService usuarioIncidentePesquisaService) {
		this.usuarioIncidentePesquisaService = usuarioIncidentePesquisaService;
	}
	
	
}

decisao.web/src/main/java/br/jus/stf/estf/decisao/objetoincidente/web/ExcluirListaProcessoActionFacesBean.java
package br.jus.stf.estf.decisao.objetoincidente.web;

import org.springframework.beans.factory.annotation.Autowired;

import br.gov.stf.estf.processostf.model.service.ListaProcessosService;
import br.gov.stf.framework.model.service.ServiceException;
import br.jus.stf.estf.decisao.pesquisa.domain.ListaIncidentesDto;
import br.jus.stf.estf.decisao.support.action.handlers.RequiresResources;
import br.jus.stf.estf.decisao.support.action.handlers.RequiresResources.Mode;
import br.jus.stf.estf.decisao.support.action.handlers.Restrict;
import br.jus.stf.estf.decisao.support.action.support.Action;
import br.jus.stf.estf.decisao.support.action.support.ActionCallback;
import br.jus.stf.estf.decisao.support.action.support.ActionIdentification;
import br.jus.stf.estf.decisao.support.action.support.ActionSupport;

@Action(id = "excluirListaProcessoActionFacesBean", 
		name = "Excluir lista de processos", 
		view = "/acoes/objetoincidente/excluirLista.xhtml", 
		height = 100, width = 500)
@Restrict({ActionIdentification.EXCLUIR_LISTA_DE_PROCESSOS})
@RequiresResources(Mode.Many)
public class ExcluirListaProcessoActionFacesBean extends ActionSupport<ListaIncidentesDto> {
	
	@Autowired
	private ListaProcessosService listaProcessosService;
	
	public void execute() {
		execute(new ActionCallback<ListaIncidentesDto>() {
			public void doInAction(ListaIncidentesDto listaProcessos) throws Exception {
				doExecute(listaProcessos);
			}
		});
		
		if(hasMessages()) {
			sendToErrors();
		} else {
			sendToConfirmation();
		}
		
		setRefresh(true);
	}
	
	protected void doExecute(ListaIncidentesDto listaProcessos) throws Exception {
		try {
			listaProcessosService.excluir(listaProcessosService.recuperarPorId(listaProcessos.getId()));
		} catch (ServiceException e) {
			addError(listaProcessos.getNome() + " - " + e.getMessage());
		}
	}
	
	@Override
	protected String getErrorTitle() {
		return "Erro ao excluir lista(s) de processos";
	}
}

decisao.web/src/main/java/br/jus/stf/estf/decisao/objetoincidente/web/ExportarProcessosActionFacesBean.java
package br.jus.stf.estf.decisao.objetoincidente.web;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;

import br.gov.stf.estf.entidade.processostf.ObjetoIncidente;
import br.jus.stf.estf.decisao.objetoincidente.service.ObjetoIncidenteService;
import br.jus.stf.estf.decisao.pesquisa.domain.ObjetoIncidenteDto;
import br.jus.stf.estf.decisao.support.action.handlers.RequiresResources;
import br.jus.stf.estf.decisao.support.action.handlers.RequiresResources.Mode;
import br.jus.stf.estf.decisao.support.action.handlers.Restrict;
import br.jus.stf.estf.decisao.support.action.support.Action;
import br.jus.stf.estf.decisao.support.action.support.ActionIdentification;


@Action(id = "exportarProcessosParaProcessosActionFacesBean", name = "Exportar Processos", view = "/acoes/objetoincidente/exportarProcessos.xhtml", width=750)
@Restrict({ ActionIdentification.EXPORTAR_PROCESSOS })
@RequiresResources(Mode.Many)
public class ExportarProcessosActionFacesBean extends  AbstractExportarProcessosActionFacesBean<ObjetoIncidenteDto> {

	@Qualifier("objetoIncidenteServiceLocal") @Autowired
	private ObjetoIncidenteService objetoIncidenteService;
	
	@Override
	protected List<ObjetoIncidente<?>> getListaObjetosIncidentes() {
		List<ObjetoIncidente<?>> objetosIncidentes = new ArrayList<ObjetoIncidente<?>>();
		for (ObjetoIncidenteDto oiDto : getResources()) {
			ObjetoIncidente<?> objetoIncidente = objetoIncidenteService.recuperarObjetoIncidentePorId(oiDto.getId());
			objetosIncidentes.add(objetoIncidente);
		}
		return objetosIncidentes;
	}	
}

decisao.web/src/main/webapp/acoes/objetoincidente/alterarLista.xhtml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:s="http://jboss.com/products/seam/taglib"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:a="http://richfaces.org/a4j"
	xmlns:c="http://java.sun.com/jstl/core"
	xmlns:stf="http://www.stf.jus.br/custom-components">

	<s:decorate id="alterarListaTextos"
		template="/acoes/support/action.template.xhtml">
		<ui:param name="facetName" value="principal" />
		<ui:define name="descricao">
			Alterar Lista de Processos
		</ui:define>
		<ui:define name="conteudo">
			<s:decorate template="/common/decorators/edit.xhtml"
				style="margin-top: 5px">
				<ui:define name="label">Nome:</ui:define>
				<h:inputText value="#{actionFacesBean.nomeNovaLista}"
					required="true"
					style="width: 250px;" />
			</s:decorate>
			<s:decorate template="/common/decorators/edit.xhtml"
				style="margin-top: 5px">
				<ui:define name="label">Ativa:</ui:define>
				<h:selectBooleanCheckbox value="#{actionFacesBean.ativa}" />
			</s:decorate>
		</ui:define>
		<ui:define name="botoes">
			<a:commandButton value="Gravar"
				action="#{actionFacesBean.execute}"
				reRender="actionModalPanel"
				oncomplete="showActionPanel('panelItem', #{actionFacesBean.definition.width}, #{actionFacesBean.definition.height})"
				eventsQueue="ajaxQueue" ignoreDupResponses="true" />
		</ui:define>
	</s:decorate>

	<s:decorate template="/acoes/support/action.template.xhtml">
		<ui:param name="facetName" value="warnings"/>
		<ui:define name="descricao">
			<h:graphicImage value="/common/images/warning.gif"/>&nbsp;&nbsp;Erro ao alterar Lista de Processos
		</ui:define> 
		<ui:define name="conteudo">
			<stf:messages level="INFO" />
		</ui:define>
		<ui:define name="botoes">
           	<a:commandButton value="Voltar" action="#{actionFacesBean.voltar}" reRender="actionModalPanel" oncomplete="showActionPanel('panelItem', #{actionFacesBean.definition.width}, #{actionFacesBean.definition.height})" eventsQueue="ajaxQueue"
							ignoreDupResponses="true"/>
		</ui:define>
	</s:decorate>
</ui:composition>

decisao.web/src/main/webapp/acoes/objetoincidente/criarLista.xhtml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:s="http://jboss.com/products/seam/taglib"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:a="http://richfaces.org/a4j"
	xmlns:c="http://java.sun.com/jstl/core"
	xmlns:stf="http://www.stf.jus.br/custom-components">

	<s:decorate id="novaListaProcessos"
		template="/acoes/support/action.template.xhtml">
		<ui:param name="facetName" value="principal" />
		<ui:define name="descricao">
			Elaborar Lista de Processos
		</ui:define>
		<ui:define name="conteudo">
			<s:decorate template="/common/decorators/edit.xhtml">
	            <ui:define name="label">Lista:</ui:define>
				<h:selectOneMenu id="lista" value="#{actionFacesBean.idListaProcessos}" required="true" style="width: 210px;">
					<f:selectItems value="#{actionFacesBean.listasDisponiveis}"/>
					<a:support  event="onchange" reRender="nomePanel, panelProcessoIncluso" eventsQueue="ajaxQueue" action="#{actionFacesBean.carregarListaProcessos}"
							ignoreDupResponses="true"/>
				</h:selectOneMenu>
			</s:decorate>
			<a:outputPanel id="nomePanel">
				<h:panelGroup rendered="#{actionFacesBean.idListaProcessos == -1}">
					<s:decorate template="/common/decorators/edit.xhtml">
			            <ui:define name="label">Nova Lista:</ui:define>
			            <h:inputText value="#{actionFacesBean.nomeNovaLista}" maxlength="80" style="width: 250px;"/>
			        </s:decorate>
		        </h:panelGroup>
	        </a:outputPanel>
	        <a:outputPanel id="panelProcesso">
				<s:decorate template="/common/decorators/edit.xhtml">
					<ui:define name="label">Processo:</ui:define>
					<h:inputText id="identificacaoProcesso"
						value="#{actionFacesBean.identificacaoProcesso}"
						onkeyup="susgestionEmptyValue(#{rich:component('sgBoxProcessoElaborarLista')},this)" 
						onclick="susgestionEmptyValue(#{rich:component('sgBoxProcessoElaborarLista')},this)"/>
					<rich:suggestionbox id="sgBoxProcessoElaborarLista"
						suggestionAction="#{incidenteFacesBean.searchWithoutFake}"
						for="identificacaoProcesso" var="result" minChars="1"
						fetchValue="#{result.identificacao}"
						nothingLabel="Nenhum Objeto Incidente encontrado." width="350"
						height="100">

						<a:support event="onselect"
							action="#{actionFacesBean.incluirProcessoSelecionado(result)}"
							reRender="panelProcessoIncluso, panelProcesso"
							focus="identificacaoProcesso" eventsQueue="ajaxQueue"
							ignoreDupResponses="true" />

						<h:column>
							<h:outputText rendered="#{result.eletronico}" value="e"
								styleClass="vermelho" />
							<h:outputText value="#{result.identificacao}"
								styleClass="oiSuggestion" />
							<h:outputText value=" -> " />
							<h:outputText value="#{result.nomeRelator}"
								styleClass="#{(result.idRelator != userFacesBean.principal.ministro.id)? 'oiSuggestion':'green'}" />
						</h:column>
					</rich:suggestionbox>
				</s:decorate>
			</a:outputPanel>
			<a:outputPanel id="panelProcessoIncluso" >
				<div style="height: 200px; overflow: auto;">
					<div style="border: 1px solid #006699; border-top: none;">
						<rich:dataTable	id="tbProcessosLista"
							var="processoValido"
							value="#{actionFacesBean.processosParaSelecao}"
							rowClasses="dr-table-row-odd, dr-table-row-even"
							styleClass="data-table">
							<rich:column styleClass="dr-table-firstcol dr-table-col-center" headerClass="dr-table-firstcol dr-table-col-center largura20px">
								<f:facet name="header">
									<a:commandButton image="/common/images/setabaixo.gif"
										action="#{actionFacesBean.selectAll}"
										eventsQueue="ajaxQueue"
										ignoreDupResponses="true"
										reRender="panelProcessoIncluso"  />
								</f:facet>
								<h:selectBooleanCheckbox styleClass="Checkbox"
									value="#{processoValido.selected}" />
							</rich:column>
							<rich:column styleClass="dr-table-lastcol" headerClass="dr-table-lastcol">
								<f:facet name="header">
									<h:outputText value="Processo" />
								</f:facet>
								<h:outputText value="#{processoValido.identificacao}" />
							</rich:column>
						</rich:dataTable>
					</div>
				</div>
			</a:outputPanel>
		</ui:define>
		<ui:define name="botoes">
			<a:commandButton value="Remover"
				action="#{actionFacesBean.excluirProcessosSelecionados}"
				reRender="panelProcessoIncluso" eventsQueue="ajaxQueue"
				ignoreDupResponses="true"
				style="float: left;"/>
			<a:commandButton value="Gravar"
				action="#{actionFacesBean.execute}"
				reRender="actionModalPanel"
				oncomplete="showActionPanel('panelItem', #{actionFacesBean.definition.width}, #{actionFacesBean.definition.height})"
				eventsQueue="ajaxQueue" ignoreDupResponses="true" />
		</ui:define>
	</s:decorate>
	
	<s:decorate template="/acoes/support/action.template.xhtml">
		<ui:param name="facetName" value="warnings"/>
		<ui:define name="descricao">
			<h:graphicImage value="/common/images/warning.gif"/>&nbsp;&nbsp;Erro ao gravar Lista de Processos
		</ui:define> 
		<ui:define name="conteudo">
			<stf:messages level="INFO" />
		</ui:define>
		<ui:define name="botoes">
           	<a:commandButton value="Voltar" action="#{actionFacesBean.voltar}" reRender="actionModalPanel" oncomplete="showActionPanel('panelItem', #{actionFacesBean.definition.width}, #{actionFacesBean.definition.height})" eventsQueue="ajaxQueue"
							ignoreDupResponses="true"/>
		</ui:define>
	</s:decorate>

</ui:composition>

decisao.web/src/main/webapp/acoes/objetoincidente/excluirProcessos.xhtml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:s="http://jboss.com/products/seam/taglib"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:rich="http://richfaces.org/rich"
    xmlns:a="http://richfaces.org/a4j"
    xmlns:c="http://java.sun.com/jstl/core">

   	<s:decorate id="excluirProcessos" template="/acoes/support/action.template.xhtml">
		<ui:param name="facetName" value="principal"/>
		<ui:define name="descricao">
			Deseja realmente excluir os registros da lista?
		</ui:define>	
		<ui:define name="botoes">
           	<a:commandButton value="OK" action="#{actionFacesBean.execute}" reRender="actionModalPanel" oncomplete="showActionPanel('panelItem', #{actionFacesBean.definition.width}, #{actionFacesBean.definition.height})" eventsQueue="ajaxQueue"
							ignoreDupResponses="true"/>
		</ui:define>
	</s:decorate>
		
</ui:composition>